#!/bin/sh

HCLIP=$(xsel -bo | head -n 4)

error () {
    zenity --question --text "Doesn't look like a URL or a file:\n$HCLIP" \
         --ok-label "Proceed Anyway" --cancel-label "Cancel" \
         --width 640
    exit $?
}

if [[ $(xsel -bo | wc -l) -gt 1 ]]; then
    error "Too many lines";
fi

case $HCLIP in
    *://*) exit 0;;
    magnet:*) exit 0;;
esac

# check if looks like a domain
perl -le '$ARGV[0] =~ /^[a-z0-9\.]+$/ || exit 1' -- "$HCLIP" \
    && exit 0

[[ -e $HCLIP ]] && exit 0

error
