#!/bin/sh
# Helper for urxvtc - "keep open" version of "urxvtc -e". Normally
# 'urxvtc -e cmd' exits as soon as it finishes contacting the daemon
# (urxvtd). This script keeps it open until cmd exits. Thanks to Marc
# Lehmann.

PID=$$

trap "exit" USR1

urxvtc -e sh -c '"$@"; kill -USR1 '$PID x "$@"

while :; do
    # NE 15 Jan 2020 what is the best way to do this? without the
    # "sleep" it eats 100% CPU
    sleep 10 &
    wait;
done

