#!/bin/bash

set -e

if [ -d tweaks.navarum ]; then
    cd tweaks.navarum
    git pull
else
    git clone https://github.com/navarum/tweaks tweaks.navarum
    cd tweaks.navarum
fi
export PREFIX=$HOME/.local
FAILED=""
for pkg in screen pulseaudio urxvt unison; do
    ./$pkg/BUILD install || FAILED="$FAILED $pkg"
done

if [ -z $FAILED ]; then
    echo "The following packages failed to install: $FAILED"
    exit 1
else
    echo "All packages succeeded"
fi
