#!/bin/bash

set -e

if [ -d tweaks.navarum ]; then
    cd tweaks.navarum
    git pull
else
    git clone https://github.com/navarum/tweaks tweaks.navarum
    cd tweaks.navarum
fi
export PREFIX=$HOME/.local
FAILED=""
if [ $# -gt 0 ]; then
    TARGETS="$@"
else
    TARGETS="screen pulseaudio urxvt unison r"
fi
for pkg in $TARGETS; do
    ./$pkg/BUILD install || FAILED="$FAILED $pkg"
done

if [ -n "$FAILED" ]; then
    echo "The following packages failed to install: $FAILED"
    echo "Rerun with:"
    echo "$0 $FAILED"
    exit 1
else
    echo "All packages succeeded:"
    echo $TARGETS
fi
